### ISSUE TITLE
toc md update with ebooks

### ISSUE THREAD

**Issue by obar1Merger** [obar1/books#12]
the `repo discovery` should create a simple __toc.md__ 

- [x]  one for each ebook with name, link to file, jog image
- [x]  in a table
- [x]  export to `toc.html`

**Comment by obar1** [comment]
the https://github.com/obar1/books/commit/f539e0a3fbd50ede8a57eabda968cc83868acd02 and https://github.com/obar1/books/commit/50af9bd6f54211eb826a39ed18cc39f0e6acdf58 were for #11
