### ISSUE TITLE
add dir generator from toc copy and apste

### ISSUE THREAD

**Issue by obar1Merger** [obar1/books#32]
at high level `copy and paste` from safari the toc and
parse that in dir file name  - the  name should be standard 
drop spaces and symbols 
ex
 `chapter "1" - txt` -> `chapter-1-txt`
ideally with `# and ## ` automatically added to readme.md
based on space and tab

**Comment by obar1** [comment]
- [ ] remove empty lines and special words entry like `index` `summary` etc
