### ISSUE TITLE
use properties files

### ISSUE THREAD

**Issue by obar1Merger** [obar1/books#95]
change `init.*` to use java properties rather then var for the core

**Comment by obar1** [comment]
well yes it;s more neat `but` 
it might be a bot challenging to implement this :( with java props ..
```
script_folder=$rootPath/app-cli/src/main/scripts
books_id=$books_folder/books_id.txt
books_id_skipped=$books_folder/books_id_skipped.txt
currv=$( cat $rootPath/app-cli/version.txt )
$rootPath/app-cli/build/libs/app-cli-$currv-all.jar
```

**Comment by obar1** [comment]
+ rework  of all the bash scripts that use  them

**Comment by obar1Merger** [comment]
ok let's  close this then
